#!/usr/bin/env bash

read -p "Enter the Database Name:     " db_name
read -p "Enter the Database Username: " db_user
# read -s -p "Enter the Database Password: "  db_password
db_password=$(openssl rand -base64 12)

psql -c "DROP DATABASE IF EXISTS $db_name"
psql -c "DROP USER IF EXISTS $db_user"
psql -c "CREATE USER $db_user PASSWORD '$db_password'"
psql -c "CREATE DATABASE $db_name OWNER $db_user"
psql -c "GRANT ALL PRIVILEGES ON DATABASE $db_name to $db_user"
psql -c "ALTER ROLE $db_user SUPERUSER"
psql -d $db_name -c "CREATE EXTENSION postgis"
psql -d $db_name -c "CREATE EXTENSION postgis_topology"

echo -e "Please note that your db password is $db_password"
